import type { Metadata } from 'next'
import '../globals.css'
import { Header } from '@/shared/components/shared/header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function HomeLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode
	modal: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body>
				<main className='min-h-screen'>
					<Header />
					{children}
					{modal}
				</main>
			</body>
		</html>
	)
}
